/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticateddashboardRouteRouteImport } from './routes/_authenticated/(dashboard)/route'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticateddashboardIndexRouteImport } from './routes/_authenticated/(dashboard)/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticateddashboardSettingsRouteRouteImport } from './routes/_authenticated/(dashboard)/settings/route'
import { Route as AuthenticateddashboardUsersIndexRouteImport } from './routes/_authenticated/(dashboard)/users/index'
import { Route as AuthenticateddashboardTasksIndexRouteImport } from './routes/_authenticated/(dashboard)/tasks/index'
import { Route as AuthenticateddashboardSettingsIndexRouteImport } from './routes/_authenticated/(dashboard)/settings/index'
import { Route as AuthenticateddashboardHelpCenterIndexRouteImport } from './routes/_authenticated/(dashboard)/help-center/index'
import { Route as AuthenticateddashboardAppsIndexRouteImport } from './routes/_authenticated/(dashboard)/apps/index'
import { Route as AuthenticateddashboardSettingsNotificationsRouteImport } from './routes/_authenticated/(dashboard)/settings/notifications'
import { Route as AuthenticateddashboardSettingsDisplayRouteImport } from './routes/_authenticated/(dashboard)/settings/display'
import { Route as AuthenticateddashboardSettingsAppearanceRouteImport } from './routes/_authenticated/(dashboard)/settings/appearance'
import { Route as AuthenticateddashboardSettingsAccountRouteImport } from './routes/_authenticated/(dashboard)/settings/account'
import { Route as AuthenticateddashboardErrorsErrorRouteImport } from './routes/_authenticated/(dashboard)/errors/$error'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticateddashboardRouteRoute =
  AuthenticateddashboardRouteRouteImport.update({
    id: '/(dashboard)',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticateddashboardIndexRoute =
  AuthenticateddashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticateddashboardRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticateddashboardSettingsRouteRoute =
  AuthenticateddashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticateddashboardRouteRoute,
  } as any)
const AuthenticateddashboardUsersIndexRoute =
  AuthenticateddashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticateddashboardRouteRoute,
  } as any)
const AuthenticateddashboardTasksIndexRoute =
  AuthenticateddashboardTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticateddashboardRouteRoute,
  } as any)
const AuthenticateddashboardSettingsIndexRoute =
  AuthenticateddashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticateddashboardSettingsRouteRoute,
  } as any)
const AuthenticateddashboardHelpCenterIndexRoute =
  AuthenticateddashboardHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticateddashboardRouteRoute,
  } as any)
const AuthenticateddashboardAppsIndexRoute =
  AuthenticateddashboardAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AuthenticateddashboardRouteRoute,
  } as any)
const AuthenticateddashboardSettingsNotificationsRoute =
  AuthenticateddashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticateddashboardSettingsRouteRoute,
  } as any)
const AuthenticateddashboardSettingsDisplayRoute =
  AuthenticateddashboardSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticateddashboardSettingsRouteRoute,
  } as any)
const AuthenticateddashboardSettingsAppearanceRoute =
  AuthenticateddashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticateddashboardSettingsRouteRoute,
  } as any)
const AuthenticateddashboardSettingsAccountRoute =
  AuthenticateddashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticateddashboardSettingsRouteRoute,
  } as any)
const AuthenticateddashboardErrorsErrorRoute =
  AuthenticateddashboardErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticateddashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings': typeof AuthenticateddashboardSettingsRouteRouteWithChildren
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/': typeof AuthenticateddashboardIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/errors/$error': typeof AuthenticateddashboardErrorsErrorRoute
  '/settings/account': typeof AuthenticateddashboardSettingsAccountRoute
  '/settings/appearance': typeof AuthenticateddashboardSettingsAppearanceRoute
  '/settings/display': typeof AuthenticateddashboardSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticateddashboardSettingsNotificationsRoute
  '/apps': typeof AuthenticateddashboardAppsIndexRoute
  '/help-center': typeof AuthenticateddashboardHelpCenterIndexRoute
  '/settings/': typeof AuthenticateddashboardSettingsIndexRoute
  '/tasks': typeof AuthenticateddashboardTasksIndexRoute
  '/users': typeof AuthenticateddashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/': typeof AuthenticateddashboardIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/errors/$error': typeof AuthenticateddashboardErrorsErrorRoute
  '/settings/account': typeof AuthenticateddashboardSettingsAccountRoute
  '/settings/appearance': typeof AuthenticateddashboardSettingsAppearanceRoute
  '/settings/display': typeof AuthenticateddashboardSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticateddashboardSettingsNotificationsRoute
  '/apps': typeof AuthenticateddashboardAppsIndexRoute
  '/help-center': typeof AuthenticateddashboardHelpCenterIndexRoute
  '/settings': typeof AuthenticateddashboardSettingsIndexRoute
  '/tasks': typeof AuthenticateddashboardTasksIndexRoute
  '/users': typeof AuthenticateddashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/(dashboard)': typeof AuthenticateddashboardRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/(dashboard)/settings': typeof AuthenticateddashboardSettingsRouteRouteWithChildren
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/(dashboard)/': typeof AuthenticateddashboardIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/(dashboard)/errors/$error': typeof AuthenticateddashboardErrorsErrorRoute
  '/_authenticated/(dashboard)/settings/account': typeof AuthenticateddashboardSettingsAccountRoute
  '/_authenticated/(dashboard)/settings/appearance': typeof AuthenticateddashboardSettingsAppearanceRoute
  '/_authenticated/(dashboard)/settings/display': typeof AuthenticateddashboardSettingsDisplayRoute
  '/_authenticated/(dashboard)/settings/notifications': typeof AuthenticateddashboardSettingsNotificationsRoute
  '/_authenticated/(dashboard)/apps/': typeof AuthenticateddashboardAppsIndexRoute
  '/_authenticated/(dashboard)/help-center/': typeof AuthenticateddashboardHelpCenterIndexRoute
  '/_authenticated/(dashboard)/settings/': typeof AuthenticateddashboardSettingsIndexRoute
  '/_authenticated/(dashboard)/tasks/': typeof AuthenticateddashboardTasksIndexRoute
  '/_authenticated/(dashboard)/users/': typeof AuthenticateddashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/'
    | '/chat'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/'
    | '/chat'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/(dashboard)'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/(dashboard)/settings'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/(dashboard)/'
    | '/_authenticated/chat/'
    | '/_authenticated/(dashboard)/errors/$error'
    | '/_authenticated/(dashboard)/settings/account'
    | '/_authenticated/(dashboard)/settings/appearance'
    | '/_authenticated/(dashboard)/settings/display'
    | '/_authenticated/(dashboard)/settings/notifications'
    | '/_authenticated/(dashboard)/apps/'
    | '/_authenticated/(dashboard)/help-center/'
    | '/_authenticated/(dashboard)/settings/'
    | '/_authenticated/(dashboard)/tasks/'
    | '/_authenticated/(dashboard)/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/(dashboard)': {
      id: '/_authenticated/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticateddashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(dashboard)/': {
      id: '/_authenticated/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticateddashboardIndexRouteImport
      parentRoute: typeof AuthenticateddashboardRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/(dashboard)/settings': {
      id: '/_authenticated/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticateddashboardSettingsRouteRouteImport
      parentRoute: typeof AuthenticateddashboardRouteRoute
    }
    '/_authenticated/(dashboard)/users/': {
      id: '/_authenticated/(dashboard)/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticateddashboardUsersIndexRouteImport
      parentRoute: typeof AuthenticateddashboardRouteRoute
    }
    '/_authenticated/(dashboard)/tasks/': {
      id: '/_authenticated/(dashboard)/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticateddashboardTasksIndexRouteImport
      parentRoute: typeof AuthenticateddashboardRouteRoute
    }
    '/_authenticated/(dashboard)/settings/': {
      id: '/_authenticated/(dashboard)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticateddashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticateddashboardSettingsRouteRoute
    }
    '/_authenticated/(dashboard)/help-center/': {
      id: '/_authenticated/(dashboard)/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticateddashboardHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticateddashboardRouteRoute
    }
    '/_authenticated/(dashboard)/apps/': {
      id: '/_authenticated/(dashboard)/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticateddashboardAppsIndexRouteImport
      parentRoute: typeof AuthenticateddashboardRouteRoute
    }
    '/_authenticated/(dashboard)/settings/notifications': {
      id: '/_authenticated/(dashboard)/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticateddashboardSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticateddashboardSettingsRouteRoute
    }
    '/_authenticated/(dashboard)/settings/display': {
      id: '/_authenticated/(dashboard)/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticateddashboardSettingsDisplayRouteImport
      parentRoute: typeof AuthenticateddashboardSettingsRouteRoute
    }
    '/_authenticated/(dashboard)/settings/appearance': {
      id: '/_authenticated/(dashboard)/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticateddashboardSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticateddashboardSettingsRouteRoute
    }
    '/_authenticated/(dashboard)/settings/account': {
      id: '/_authenticated/(dashboard)/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticateddashboardSettingsAccountRouteImport
      parentRoute: typeof AuthenticateddashboardSettingsRouteRoute
    }
    '/_authenticated/(dashboard)/errors/$error': {
      id: '/_authenticated/(dashboard)/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticateddashboardErrorsErrorRouteImport
      parentRoute: typeof AuthenticateddashboardRouteRoute
    }
  }
}

interface AuthenticateddashboardSettingsRouteRouteChildren {
  AuthenticateddashboardSettingsAccountRoute: typeof AuthenticateddashboardSettingsAccountRoute
  AuthenticateddashboardSettingsAppearanceRoute: typeof AuthenticateddashboardSettingsAppearanceRoute
  AuthenticateddashboardSettingsDisplayRoute: typeof AuthenticateddashboardSettingsDisplayRoute
  AuthenticateddashboardSettingsNotificationsRoute: typeof AuthenticateddashboardSettingsNotificationsRoute
  AuthenticateddashboardSettingsIndexRoute: typeof AuthenticateddashboardSettingsIndexRoute
}

const AuthenticateddashboardSettingsRouteRouteChildren: AuthenticateddashboardSettingsRouteRouteChildren =
  {
    AuthenticateddashboardSettingsAccountRoute:
      AuthenticateddashboardSettingsAccountRoute,
    AuthenticateddashboardSettingsAppearanceRoute:
      AuthenticateddashboardSettingsAppearanceRoute,
    AuthenticateddashboardSettingsDisplayRoute:
      AuthenticateddashboardSettingsDisplayRoute,
    AuthenticateddashboardSettingsNotificationsRoute:
      AuthenticateddashboardSettingsNotificationsRoute,
    AuthenticateddashboardSettingsIndexRoute:
      AuthenticateddashboardSettingsIndexRoute,
  }

const AuthenticateddashboardSettingsRouteRouteWithChildren =
  AuthenticateddashboardSettingsRouteRoute._addFileChildren(
    AuthenticateddashboardSettingsRouteRouteChildren,
  )

interface AuthenticateddashboardRouteRouteChildren {
  AuthenticateddashboardSettingsRouteRoute: typeof AuthenticateddashboardSettingsRouteRouteWithChildren
  AuthenticateddashboardIndexRoute: typeof AuthenticateddashboardIndexRoute
  AuthenticateddashboardErrorsErrorRoute: typeof AuthenticateddashboardErrorsErrorRoute
  AuthenticateddashboardAppsIndexRoute: typeof AuthenticateddashboardAppsIndexRoute
  AuthenticateddashboardHelpCenterIndexRoute: typeof AuthenticateddashboardHelpCenterIndexRoute
  AuthenticateddashboardTasksIndexRoute: typeof AuthenticateddashboardTasksIndexRoute
  AuthenticateddashboardUsersIndexRoute: typeof AuthenticateddashboardUsersIndexRoute
}

const AuthenticateddashboardRouteRouteChildren: AuthenticateddashboardRouteRouteChildren =
  {
    AuthenticateddashboardSettingsRouteRoute:
      AuthenticateddashboardSettingsRouteRouteWithChildren,
    AuthenticateddashboardIndexRoute: AuthenticateddashboardIndexRoute,
    AuthenticateddashboardErrorsErrorRoute:
      AuthenticateddashboardErrorsErrorRoute,
    AuthenticateddashboardAppsIndexRoute: AuthenticateddashboardAppsIndexRoute,
    AuthenticateddashboardHelpCenterIndexRoute:
      AuthenticateddashboardHelpCenterIndexRoute,
    AuthenticateddashboardTasksIndexRoute:
      AuthenticateddashboardTasksIndexRoute,
    AuthenticateddashboardUsersIndexRoute:
      AuthenticateddashboardUsersIndexRoute,
  }

const AuthenticateddashboardRouteRouteWithChildren =
  AuthenticateddashboardRouteRoute._addFileChildren(
    AuthenticateddashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticateddashboardRouteRoute: typeof AuthenticateddashboardRouteRouteWithChildren
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticateddashboardRouteRoute:
    AuthenticateddashboardRouteRouteWithChildren,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
